server:
  port: 5000
spring:
  profiles:
    active: default
---
spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    initialize: true
    max-wait: 10000
    initial-size: 34
    max-active: 50
    test-on-borrow: false
    test-while-idle: true
    max-idle: 200
    min-idle: 89
    remove-abandoned: true
    remove-abandoned-timeout: 50
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  amazon:
    s3:
      default-bucket: zamrad-photos-dev

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/${MYSQL_ENV_MYSQL_DATABASE}
    username: ${MYSQL_ENV_MYSQL_USER}
    password: ${MYSQL_ENV_MYSQL_PASSWORD}
    initialize: true
    max-wait: 10000
    initial-size: 34
    max-active: 50
    test-on-borrow: false
    test-while-idle: true
    max-idle: 200
    min-idle: 89
    remove-abandoned: true
    remove-abandoned-timeout: 50
  jpa:
   database-platform: org.hibernate.dialect.MySQLDialect
   generate-ddl: true
   hibernate:
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
server:
  port: 8080
---
spring:
  profiles: test
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,
      org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration